from app.api.nsmodels.auth import (
    auth_ns,
    registration_parser,
    auth_parser,
    request_reset_password_parser,
    reset_password_parser,
    change_password_parser,
)
from app.api.nsmodels.accounts import (
    accounts_ns,
    account_model,
    current_user_model,
    account_update_parser,
    account_update_response_model,
    account_list_response_model,
    account_delete_response_model,
    grant_permissions_parser,
    permission_model,
    user_permission_model,
    permission_list_response_model,
    user_permission_list_response_model,
    permission_action_response_model,
    error_model,
)
from app.api.nsmodels.permissions import (
    permissions_ns,
    permission_create_parser,
    permission_model as catalog_permission_model,
    permission_list_response_model as catalog_permission_list_response_model,
    permission_create_response_model,
    permission_delete_response_model,
    error_model as permissions_error_model,
    JWT_OR_API_KEY as PERMISSIONS_JWT_OR_API_KEY,
)
from app.api.nsmodels.recips import (
    recips_ns,
    recip_model,
    recip_email_model,
    recip_number_model,
    recip_create_parser,
    recip_update_parser,
    recip_email_create_parser,
    recip_email_update_parser,
    recip_number_create_parser,
    recip_number_update_parser,
    recip_response_model,
    recip_list_response_model,
    recip_email_response_model,
    recip_number_response_model,
    message_response_model,
)
from app.api.nsmodels.services import (
    services_ns,
    register_service_parser,
    service_model,
    service_list_response_model,
    service_register_response_model,
    message_response_model as service_message_response_model,
    error_model as service_error_model,
    JWT_OR_API_KEY,
)
from app.api.nsmodels.seismic_events import (
    seismic_events_ns,
    seismic_event_model,
    seismic_event_list_response_model,
    seismic_event_response_model,
    event_magnitude_model,
    event_magnitude_response_model,
    event_beachball_model,
    event_beachball_response_model,
    magnitude_catalog_list_response_model,
    message_response_model as seismic_message_response_model,
    error_model as seismic_error_model,
    seismic_event_create_parser,
    seismic_event_update_parser,
    event_magnitude_create_parser,
    event_magnitude_update_parser,
    event_beachball_parser,
    JWT_OR_API_KEY as SEISMIC_JWT_OR_API_KEY,
)
from app.api.nsmodels.publish_events import (
    publish_events_ns,
    publish_event_response_model,
    published_events_list_response_model,
    error_model as publish_events_error_model,
    JWT_OR_API_KEY as PUBLISH_EVENTS_JWT_OR_API_KEY,
)
from app.api.nsmodels.alert_zones import (
    alert_zones_ns,
    alert_zone_model,
    alert_zone_create_model,
    alert_zone_update_model,
    alert_zone_response_model,
    alert_zone_list_response_model,
    message_response_model as alert_zone_message_response_model,
    error_model as alert_zone_error_model,
    JWT_OR_API_KEY as ALERT_ZONES_JWT_OR_API_KEY,
)
